service: secret-santa

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev

functions:
  wishlist:
    handler: handler.wishlist
    events:
      - http:
          path: /wishlist/{id}
          method: get
          cors: true

  index:
    handler: handler.index
    events:
      - http:
          path: /
          method: get
          cors: true

  handleWishlistSubmision:
    handler: handler.handleWishlistSubmision
    events:
      - http:
          path: /wishlist/{id}/form
          method: post
          cors: true

  handlePairCreation:
    handler: handler.handlePairCreation
    events:
      - http:
          path: /form
          method: post
          cors: true
